# Generated by Django 2.2.12 on 2020-12-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Canceled'), (2, 'Accepted')], default=0),
        ),
        migrations.AlterField(
            model_name='voting',
            name='type',
            field=models.IntegerField(choices=[(0, 'Checkboxes'), (1, 'Radios'), (2, 'Buttons')], default=0),
        ),
    ]
