# Generated by Django 3.1.4 on 2021-01-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201219_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='image',
            field=models.FileField(null=True, upload_to='votings'),
        ),
    ]
