# Generated by Django 3.1.4 on 2021-01-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210102_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='image',
            field=models.ImageField(default='/votings/No-image.png', null=True, upload_to='votings'),
        ),
    ]
