# Generated by Django 3.1.4 on 2021-01-08 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20210103_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='image',
            field=models.ImageField(default='votings/No-image.png', null=True, upload_to='votings'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='users/No-image.png', null=True, upload_to='users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
