# Generated by Django 3.1.4 on 2021-01-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210110_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='votefact',
            name='variants',
            field=models.ManyToManyField(to='main.VoteVariant'),
        ),
    ]
