# Generated by Django 3.2.5 on 2021-07-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_move_votefact_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='next_voting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextttttt_voting', to='main.voting'),
        ),
        migrations.AddField(
            model_name='voting',
            name='prev_voting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prevvvvvv_voting', to='main.voting'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='votings'),
        ),
    ]
