# Generated by Django 3.2.5 on 2021-07-18 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210718_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='next_voting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_voting', to='main.voting'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='prev_voting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_voting', to='main.voting'),
        ),
    ]
