# Generated by Django 3.2.5 on 2021-07-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_voting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='votings'),
        ),
    ]
